# Generated by Django 2.2.1 on 2019-06-03 00:41

import time
from django.db import migrations
from nba_py import team


def load_team_data(apps, schema_editor):
    Team = apps.get_model("main", "Team")

    teams_df = team.TeamList().info()
    for team_id in teams_df['TEAM_ID'].values[:30]:
        data = team.TeamSummary(team_id=team_id).info()
        Team(
            team_id=data['TEAM_ID'].values[0],
            team_abb=data['TEAM_ABBREVIATION'][0],
            team_conf=data['TEAM_CONFERENCE'][0],
            team_div=data['TEAM_DIVISION'][0],
            team_city=data['TEAM_CITY'][0],
            team_name=data['TEAM_NAME'][0]
        ).save()
        time.sleep(1)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_team_data)
    ]
