# Generated by Django 2.2.3 on 2019-07-09 19:18

from django.db import migrations
from simplejson import load


def load_team_data(apps, schema_editor):
    Team = apps.get_model("main", "Team")

    with open('data/team_list.json') as f:
        teams = load(f)

    for team_id in teams['TEAM_ID'].values():
        with open(f'data/team_summary/{team_id}.json') as f:
            data = load(f)

        Team(
            team_id=data['TEAM_ID'].values,
            team_abb=data['TEAM_ABBREVIATION'],
            team_conf=data['TEAM_CONFERENCE'],
            team_div=data['TEAM_DIVISION'],
            team_city=data['TEAM_CITY'],
            team_name=data['TEAM_NAME']
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_team_data)
    ]
