# Generated by Django 2.2.4 on 2019-08-07 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerseasonstats',
            options={'ordering': ['-season']},
        ),
    ]
