# Generated by Django 2.2.4 on 2019-08-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playergamelog',
            options={'ordering': ['-game', 'order']},
        ),
        migrations.RemoveField(
            model_name='playergamelog',
            name='team_game_log',
        ),
    ]
