# Generated by Django 2.2.4 on 2019-08-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190808_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamelog',
            name='curr_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='curr_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.Team'),
        ),
    ]
