# Generated by Django 2.2.3 on 2019-07-09 19:30

from django.db import migrations
from simplejson import load


def load_player_data(apps, schema_editor):
    Player = apps.get_model("main", "Player")

    with open('data/player_list.json') as f:
        players = load(f)

    for player_id in players['PERSON_ID'].values():
        try:
            with open(f'data/player_summary/{player_id}.json') as f:
                data = load(f)
        except FileNotFoundError:
            continue

        Player(
            team=apps.get_model("main", "Team").objects.filter(team_id=data['TEAM_ID'][0])[0],
            first_name=data['FIRST_NAME'][0],
            last_name=data['LAST_NAME'][0],
            birth_date=data['BIRTHDATE'][0][:10],
            player_id=data['PERSON_ID'][0],
            draft_year=data['DRAFT_YEAR'][0],
            draft_round=data['DRAFT_ROUND'][0],
            draft_number=data['DRAFT_NUMBER'][0],
            position=data['POSITION'][0],
            jersey=0 if data['JERSEY'][-1] == '' else int(data['JERSEY'][-1]),
            height=data['HEIGHT'][0],
            weight=int(data['WEIGHT'][0]),
            school=data['SCHOOL'][0],
            country=data['COUNTRY'][0]
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_team_player_data'),
    ]

    operations = [
        migrations.RunPython(load_player_data)
    ]
