# Generated by Django 2.2.3 on 2019-07-10 02:17

import pandas as pd
from django.db import migrations


def load_player_data(apps, schema_editor):
    Player = apps.get_model("main", "Player")
    Team = apps.get_model("main", "Team")

    print("Migrate Individual Player Data.")

    leaders = pd.read_json('main/data/2018-19/player_leaders.json')  # type: pd.DataFrame
    player_summary = pd.read_json('main/data/2018-19/player_summary.json')  # type: pd.DataFrame
    for data in player_summary.itertuples(index=False):
        filtered_rank = leaders[leaders.PLAYER_ID == data.PERSON_ID].RANK.values
        player_rank = filtered_rank[0] if len(filtered_rank) > 0 else -1
        school = "N/A" if data.SCHOOL is None or data.SCHOOL == ' ' else data.SCHOOL

        Player(
            team=Team.objects.get(team_id=data.TEAM_ID),
            first_name=data.FIRST_NAME,
            last_name=data.LAST_NAME,
            birth_date=data.BIRTHDATE[:10],
            player_id=data.PERSON_ID,
            draft_year=data.DRAFT_YEAR,
            draft_round=data.DRAFT_ROUND,
            draft_number=data.DRAFT_NUMBER,
            position=data.POSITION,
            jersey=0 if data.JERSEY == '' else int(data.JERSEY),
            height=data.HEIGHT,
            weight=int(data.WEIGHT),
            school=school,
            country=data.COUNTRY,
            season_exp=data.SEASON_EXP
        ).save()


def undo(apps, schema_editor):
    Player = apps.get_model("main", "Player")
    Player.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_populate_team_data'),
    ]

    operations = [
        migrations.RunPython(load_player_data, undo)
    ]
