# Generated by Django 2.2.4 on 2019-08-09 15:02

import pandas as pd
from django.db import migrations


def load_data(apps, schema_editor):
    PlayerGameLog = apps.get_model('main', 'PlayerGameLog')
    Team = apps.get_model('main', 'Team')
    Player = apps.get_model('main', 'Player')
    Game = apps.get_model('main', 'Game')

    data = pd.read_json('main/data/2018-19/player_game_log.json', dtype={'GAME_ID': str})
    for player_data in data.itertuples():
        try:
            player = Player.objects.get(pk=player_data.PLAYER_ID)
        except Player.DoesNotExist:
            continue

        print(player_data)
        game_obj = PlayerGameLog.objects.get(
            player=player,
            game=Game.objects.get(pk=player_data.GAME_ID)
        )
        game_obj.curr_team = Team.objects.get(pk=player_data.TEAM_ID)
        game_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190809_1038'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
