# Generated by Django 2.2.1 on 2019-06-03 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_player_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
