# Generated by Django 2.2.4 on 2019-08-07 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190806_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playergamelog',
            options={'ordering': ['-game']},
        ),
        migrations.AlterModelOptions(
            name='teamgamelog',
            options={'ordering': ['-game']},
        ),
    ]
