# Generated by Django 2.2.3 on 2019-07-11 01:53

from django.db import migrations


def load_data(apps, schema_editor):
    pass


def undo(apps, schema_editor):
    PlayerGameLog = apps.get_model("main", "PlayerGameLog")
    PlayerGameLog.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_populate_team_game_log_data'),
    ]

    operations = [
        migrations.RunPython(load_data, undo)
    ]
