# Generated by Django 2.2.1 on 2019-06-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_player_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='season_exp',
            field=models.IntegerField(default=0),
        ),
    ]
