# Generated by Django 2.2.3 on 2019-08-04 01:05
import pandas as pd
from django.db import migrations


def load_data(apps, schema_editor):
    Standing = apps.get_model('main', 'Standing')
    Team = apps.get_model('main', 'Team')

    print("Migrate Standing Data.")

    data = pd.read_json('main/data/2018-19/standing.json').round(3)  # type: pd.DataFrame
    for team_data in data.itertuples(index=False):

        Standing(
            team=Team.objects.get(team_id=team_data.TEAM_ID),
            wins=team_data.W,
            losses=team_data.L,
            win_percent=team_data.W_PCT,
            home_record=team_data.HOME_RECORD,
            away_record=team_data.ROAD_RECORD
        ).save()


def undo(apps, schema_editor):
    Standing = apps.get_model('main', 'Standing')
    Standing.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_populate_season_stats_data'),
    ]

    operations = [
        migrations.RunPython(load_data, undo)
    ]
