# Generated by Django 2.2.1 on 2019-06-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_player_season_exp'),
    ]

    operations = [
    ]
