# Generated by Django 2.2.1 on 2019-06-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_add_player_season_exp'),
    ]

    operations = [
    ]
