# Generated by Django 2.2.1 on 2019-06-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_fix_previous_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='conf_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='div_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='nba_debut',
            field=models.CharField(default=4, max_length=4),
        ),
        migrations.AddField(
            model_name='team',
            name='season_year',
            field=models.CharField(default='2018-19', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
