# Generated by Django 2.2.1 on 2019-06-11 01:01

import time
from django.db import migrations
from nba_py import team


def load_team_data(apps, schema_editor):
    Team = apps.get_model("main", "Team")

    teams_df = team.TeamList().info()
    for team_id in teams_df['TEAM_ID'].values[:30]:
        team_obj = Team.objects.filter(team_id=team_id)[0]
        data = team.TeamSummary(team_id=team_id).info()
        team_obj.wins = data['W'][0]
        team_obj.losses = data['L'][0]
        team_obj.conf_rank = data['CONF_RANK'][0]
        team_obj.div_rank = data['DIV_RANK'][0]
        team_obj.season_year = data['SEASON_YEAR'][0]
        team_obj.nba_debut = data['MIN_YEAR'][0]
        team_obj.save()

        time.sleep(1)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_add_more_fields_team'),
    ]

    operations = [
        migrations.RunPython(load_team_data)
    ]
