# Generated by Django 2.2.1 on 2019-06-29 03:21

from django.db import migrations


def load_data(apps, schema_editor):
    Player = apps.get_model("main", "Player")

    for player in Player.objects.all():
        if player.school is None:
            player.school = "N/A"
            player.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_add_player_rank_data'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
