# Generated by Django 2.2.2 on 2019-06-30 21:56

import time

from django.db import migrations
from nba_py import player


def load_data(apps, schema_editor):
    PlayerGameLog = apps.get_model('main', 'PlayerGameLog')
    Players = apps.get_model('main', 'Player')
    for player_obj in Players.objects.all():
        data = player.PlayerGameLogs(player_obj.player_id).info()

        print(f"{player_obj.first_name} {player_obj.last_name}")

        for _, player_data in data.iterrows():
            PlayerGameLog(
                player=player_obj,
                plus_minus=player_data['PLUS_MINUS'],
                game_date=player_data['GAME_DATE'],
                matchup=player_data['MATCHUP'],
                minutes=player_data['MIN'],
                points=player_data['PTS'],
                offense_reb=player_data['OREB'],
                defense_reb=player_data['DREB'],
                rebounds=player_data['REB'],
                assists=player_data['AST'],
                steals=player_data['STL'],
                blocks=player_data['BLK'],
                turnovers=player_data['TOV'],
                fouls=player_data['PF'],
                fg_made=player_data['FGM'],
                fg_attempt=player_data['FGA'],
                fg_percent=player_data['FG_PCT'],
                fg3_made=player_data['FG3M'],
                fg3_attempt=player_data['FG3A'],
                fg3_percent=player_data['FG3_PCT'],
                ft_made=player_data['FTM'],
                ft_attempt=player_data['FTA'],
                ft_percent=player_data['FT_PCT'],
                result=player_data['WL']
            ).save()

        time.sleep(1)


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0016_add_games_data'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
