# Generated by Django 2.2.3 on 2019-07-01 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_add_player_game_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='dnp_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_stats',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team_stats',
        ),
    ]
