# Generated by Django 2.2.3 on 2019-07-02 01:15

import time

from django.db import migrations
from nba_py import team


def load_data(apps, schema_editor):
    Game = apps.get_model('main', 'Game')
    Teams = apps.get_model('main', 'Team')

    game_ids = set([])
    for team_obj in Teams.objects.all():
        data = team.TeamGameLogs(team_obj.team_id, season='2018-19').info()

        for game_id in data.get("Game_ID"):
            print(game_id)
            game_ids.add(game_id)
            time.sleep(0.5)

    for game_id in game_ids:
        Game(game_id=game_id).save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0021_remove_game_dnp_players'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
