# Generated by Django 2.2.3 on 2019-07-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_game_dnp_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='dnp_players',
        ),
        migrations.AddField(
            model_name='game',
            name='dnp_players',
            field=models.ManyToManyField(to='main.Player'),
        ),
    ]
