# Generated by Django 2.2.3 on 2019-07-06 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_add_start_field'),
    ]

    operations = [
    ]
