# Generated by Django 2.2.3 on 2019-07-06 00:47

import json
import time

import math
from django.db import migrations
from nba_py import game


def load_data(apps, schema_editor):
    Game = apps.get_model('main', 'Game')

    for game_obj in Game.objects.all():
        print(game_obj.game_id)
        data = game.Boxscore(game_obj.game_id).player_stats()

        dnp_players = [p_data['PLAYER_ID'] for _, p_data in data.iterrows() if math.isnan(p_data['PF'])]
        order = [p_data['PLAYER_ID'] for _, p_data in data.iterrows() if not math.isnan(p_data['PF'])]
        game_obj.dnp_players = json.dumps(dnp_players)
        game_obj.starters = json.dumps(order)
        game_obj.save()
        time.sleep(0.5)


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0027_add_start_field'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
