# Generated by Django 2.2.3 on 2019-07-06 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_added_per_quarter_pts'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='away', to='main.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='main.Team'),
            preserve_default=False,
        ),
    ]
