# Generated by Django 2.2.3 on 2019-07-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_added_home_away_team_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamgamelog',
            old_name='quarter1_pts',
            new_name='pts_q1',
        ),
        migrations.RenameField(
            model_name='teamgamelog',
            old_name='quarter2_pts',
            new_name='pts_q2',
        ),
        migrations.RenameField(
            model_name='teamgamelog',
            old_name='quarter3_pts',
            new_name='pts_q3',
        ),
        migrations.RenameField(
            model_name='teamgamelog',
            old_name='quarter4_pts',
            new_name='pts_q4',
        ),
        migrations.AddField(
            model_name='teamgamelog',
            name='pts_ot1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamgamelog',
            name='pts_ot2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamgamelog',
            name='pts_ot3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamgamelog',
            name='pts_ot4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
