# Generated by Django 2.2.3 on 2019-07-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_added_ot_pts_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='starters',
            new_name='order',
        ),
        migrations.AddField(
            model_name='game',
            name='inactive_players',
            field=models.TextField(blank=True, null=True),
        ),
    ]
