# Generated by Django 2.2.3 on 2019-07-06 20:54

import time

from django.db import migrations
from nba_py import game


def load_data(apps, schema_editor):
    Game = apps.get_model('main', 'Game')

    for game_obj in Game.objects.all():
        print(game_obj.game_id)
        data = game.BoxscoreSummary(game_obj.game_id).line_score()

        for _, line in data.iterrows():
            game_log_obj = game_obj.teamgamelog_set.filter(team__team_id=line['TEAM_ID'])[0]
            game_log_obj.pts_q1 = line['PTS_QTR1']
            game_log_obj.pts_q2 = line['PTS_QTR2']
            game_log_obj.pts_q3 = line['PTS_QTR3']
            game_log_obj.pts_q4 = line['PTS_QTR4']
            game_log_obj.pts_ot1 = line['PTS_OT1']
            game_log_obj.pts_ot2 = line['PTS_OT2']
            game_log_obj.pts_ot3 = line['PTS_OT3']
            game_log_obj.pts_ot4 = line['PTS_OT4']
            game_log_obj.save()

            time.sleep(0.2)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_add_inactive_player'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
