# Generated by Django 2.2.3 on 2019-07-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_add_per_quarter_pts_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='season_exp',
            field=models.IntegerField(),
        ),
    ]
