# Generated by Django 2.2.3 on 2019-07-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_made_player_rank_field_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_date',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='matchup',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
